version: "3"
services:
  mysqldb:
    image: library/mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - "mysql-airflow-data:/var/lib/mysql"
  airflow-local:
    build: .
    container_name: airflow-local
    restart: on-failure:10
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - "./airflow:/home/airflow_user/airflow/"
    depends_on:
      - "mysqldb"
volumes:
  mysql-airflow-data:
