version: "2.4"
services:
  # MySQL
  mysqldb:
    image: library/mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - "mysql-airflow-data:/var/lib/mysql"
    mem_limit:  2G

  # Airflow Scheduler Service
  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    restart: on-failure
    ports:
      - "8090:8080"
    env_file:
      - .env
    volumes:
      - "./airflow:/home/airflow_files/airflow/"
    depends_on:
      - "mysqldb"
    mem_limit: 4G
    command: "bash start-scheduler.sh"

  # Airflow Webserver
  airflow-webserver:
    build: .
    container_name: airflow-webserver
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysqldb
      - airflow-scheduler
    command: "bash start-server.sh"

volumes:
  mysql-airflow-data:
    driver: local
